### ISSUE TITLE
want use server only

### ISSUE THREAD

**Issue by ZYWH-tech** [nuance1979/llama-server#12]
I want to use only the server program, can you provide the documentation of the server program, including several interfaces, corresponding request and response JSON samples, thank you

**Comment by nuance1979** [comment]
My server only implemented a minimal subset of [OpenAI APIs](https://platform.openai.com/docs/api-reference).
For a more complete API implementation, I would recommend https://github.com/abetlen/llama-cpp-python#web-server .

**Comment by ZYWH-tech** [comment]
thanks a lot
